# kubectl apply -f 3-mongodb_demo/mongodb-secret.yml
# kubectl get secret
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongo-root-username: YWRtaW4= # echo -n 'admin' | base64
  mongo-root-password: YWRtaW4=