### Deployment definition ---
apiVersion: apps/v1
kind: Deployment
# Deployment definition
metadata:
  name: mongo-express
  labels:
    app: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    # Pod definition
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
        - name: mongo-express
          image: mongo-express
          # Define MongoDB Connection
          ports:
            - containerPort: 8081
          env:
          # Get connection admin user name from secrets
          - name: ME_CONFIG_MONGODB_ADMINUSERNAME
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: mongo-root-username
          # Get connection admin password from secrets
          - name: ME_CONFIG_MONGODB_ADMINPASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb-secret
                key: mongo-root-password
          # Get connection server name from config map
          - name: ME_CONFIG_MONGODB_SERVER
            valueFrom:
              configMapKeyRef:
                name: mongodb-configmap
                key: database_url
---
# Service to access deployment ---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
spec:
  selector:
    app: mongo-express
  type: LoadBalancer # External service load balancer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081 
      nodePort: 30000 # The port where the external ip address will be opened - used in browser - 30000-32767